name = "sistemazm-backend"
main = "worker.py"
compatibility_date = "2024-04-03"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "sistemazm_db"
database_id = "change_me_to_your_d1_database_uuid"
